# Generated by Django 5.0.3 on 2024-03-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansione', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateField()),
                ('livello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.level')),
            ],
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.task')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('datanascita', models.DateField()),
                ('carriera', models.ManyToManyField(through='hrm.Career', to='hrm.level')),
                ('incarichi', models.ManyToManyField(through='hrm.Assignments', to='hrm.task')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='lavoratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.worker'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='lavoratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.worker'),
        ),
    ]
