# Generated by Django 5.0.3 on 2024-03-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='costo_ora_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='TimeRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField()),
                ('ore_diurne_figurative', models.IntegerField()),
                ('ore_diurne_reali', models.IntegerField()),
                ('ore_notturne_figurative', models.IntegerField()),
                ('ore_notturne_reali', models.IntegerField()),
                ('commessa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='job.contract')),
                ('lavoratore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.worker')),
            ],
        ),
    ]
