# Generated by Django 5.0.3 on 2024-04-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_level_costo_ora_base_timerecording'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['cognome', 'nome']},
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='datanascita',
            new_name='data_nascita',
        ),
    ]
