# Generated by Django 5.0.3 on 2024-04-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Employee',
        ),
    ]
