# Generated by Django 5.0.3 on 2024-03-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_commessa', models.CharField(max_length=8)),
                ('nome_commessa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_ca', models.CharField(max_length=8)),
                ('nome_ca', models.CharField(max_length=50)),
                ('inizio_lavori', models.DateField()),
                ('fine_lavori', models.DateField()),
                ('commessa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.contract')),
            ],
        ),
    ]
